-- MySQL Script generated by MySQL Workbench
-- Fri Sep  3 00:16:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema maturaarbeit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maturaarbeit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maturaarbeit` DEFAULT CHARACTER SET utf8 ;
USE `maturaarbeit` ;

-- -----------------------------------------------------
-- Table `maturaarbeit`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maturaarbeit`.`user` (
                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                     `name` VARCHAR(255) NOT NULL,
                                                     PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maturaarbeit`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maturaarbeit`.`test` (
                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                     `url` VARCHAR(255) NOT NULL,
                                                     `finished` TINYINT NOT NULL,
                                                     `create_date` DATETIME NOT NULL,
                                                     `start_date` DATETIME NULL,
                                                     `complete_date` DATETIME NULL,
                                                     `sleep_quality` TINYINT NULL,
                                                     `sleep_start` DATETIME NULL,
                                                     `sleep_end` DATETIME NULL,
                                                     `drugs` TINYINT NULL,
                                                     `user_id` INT NOT NULL,
                                                     PRIMARY KEY (`id`),
                                                     INDEX `fk_test_user1_idx` (`user_id` ASC) VISIBLE,
                                                     CONSTRAINT `fk_test_user1`
                                                         FOREIGN KEY (`user_id`)
                                                             REFERENCES `maturaarbeit`.`user` (`id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maturaarbeit`.`icons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maturaarbeit`.`icons` (
                                                      `id` INT NOT NULL AUTO_INCREMENT,
                                                      `icon_no` INT NOT NULL,
                                                      `icon_id` INT NOT NULL,
                                                      `test_id` INT NOT NULL,
                                                      PRIMARY KEY (`id`),
                                                      INDEX `fk_icons_test1_idx` (`test_id` ASC) VISIBLE,
                                                      CONSTRAINT `fk_icons_test1`
                                                          FOREIGN KEY (`test_id`)
                                                              REFERENCES `maturaarbeit`.`test` (`id`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maturaarbeit`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maturaarbeit`.`answers` (
                                                        `id` INT NOT NULL AUTO_INCREMENT,
                                                        `answer_no` INT NOT NULL,
                                                        `user_input` INT NULL,
                                                        `test_id` INT NOT NULL,
                                                        `icons_id` INT NOT NULL,
                                                        PRIMARY KEY (`id`),
                                                        INDEX `fk_answers_test_idx` (`test_id` ASC) VISIBLE,
                                                        INDEX `fk_answers_icons1_idx` (`icons_id` ASC) VISIBLE,
                                                        CONSTRAINT `fk_answers_test`
                                                            FOREIGN KEY (`test_id`)
                                                                REFERENCES `maturaarbeit`.`test` (`id`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION,
                                                        CONSTRAINT `fk_answers_icons1`
                                                            FOREIGN KEY (`icons_id`)
                                                                REFERENCES `maturaarbeit`.`icons` (`id`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
